resources:
- deployment.yaml
- service.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- name: webhooks-api-env
  literals:
    - OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES=true
    - OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES=true
    - OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY=in_memory
    - ASPNETCORE_FORWARDEDHEADERS_ENABLED=true
    - HTTP_PORTS=8080
    - ConnectionStrings__eventbus=amqp://guest:UZtuVZiBkqhbD4Ljs0BbG7@eventbus:5672
    - ConnectionStrings__webhooksdb=Host=postgres;Port=5432;Username=postgres;Password=LjJef4uOIXfwG5cUnDuFuC;Database=webhooksdb
    - DisableAuth=true
    - OTEL_EXPORTER_OTLP_ENDPOINT=http://aspire-dashboard:18889
    - OTEL_SERVICE_NAME=webhooks-api
    - ASPNETCORE_URLS=http://+:8080;

